#!/bin/bash
cleos='/usr/local/bin/cleos -u http://47.101.139.226:8888'

# create system account
$cleos create account eosio eosio.msig 	EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
$cleos create account eosio eosio.names EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
$cleos create account eosio eosio.ram 	EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
$cleos create account eosio eosio.ramfee EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
$cleos create account eosio eosio.saving EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
$cleos create account eosio eosio.stake EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
$cleos create account eosio eosio.token EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
$cleos create account eosio eosio.upay 	EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV

# create user account
$cleos create account eosio alice EOS7tdB5cKCjhjZqyMNY9deCKD6CsHnxbdY9XE8k5vgAt3gLJwQWh
$cleos create account eosio bob EOS7tdB5cKCjhjZqyMNY9deCKD6CsHnxbdY9XE8k5vgAt3gLJwQWh
$cleos create account eosio lurpis EOS7tdB5cKCjhjZqyMNY9deCKD6CsHnxbdY9XE8k5vgAt3gLJwQWh
$cleos create account eosio hello EOS7tdB5cKCjhjZqyMNY9deCKD6CsHnxbdY9XE8k5vgAt3gLJwQWh
$cleos create account eosio addressbook EOS7tdB5cKCjhjZqyMNY9deCKD6CsHnxbdY9XE8k5vgAt3gLJwQWh
$cleos create account eosio abcounter EOS7tdB5cKCjhjZqyMNY9deCKD6CsHnxbdY9XE8k5vgAt3gLJwQWh
$cleos create account eosio testa EOS7tdB5cKCjhjZqyMNY9deCKD6CsHnxbdY9XE8k5vgAt3gLJwQWh
$cleos create account eosio testb EOS7tdB5cKCjhjZqyMNY9deCKD6CsHnxbdY9XE8k5vgAt3gLJwQWh
$cleos create account eosio testc EOS7tdB5cKCjhjZqyMNY9deCKD6CsHnxbdY9XE8k5vgAt3gLJwQWh
$cleos create account eosio testd EOS7tdB5cKCjhjZqyMNY9deCKD6CsHnxbdY9XE8k5vgAt3gLJwQWh
$cleos create account eosio teste EOS7tdB5cKCjhjZqyMNY9deCKD6CsHnxbdY9XE8k5vgAt3gLJwQWh
$cleos create account eosio testf EOS7tdB5cKCjhjZqyMNY9deCKD6CsHnxbdY9XE8k5vgAt3gLJwQWh
$cleos create account eosio testg EOS7tdB5cKCjhjZqyMNY9deCKD6CsHnxbdY9XE8k5vgAt3gLJwQWh
$cleos create account eosio testh EOS7tdB5cKCjhjZqyMNY9deCKD6CsHnxbdY9XE8k5vgAt3gLJwQWh
$cleos create account eosio testi EOS7tdB5cKCjhjZqyMNY9deCKD6CsHnxbdY9XE8k5vgAt3gLJwQWh
$cleos create account eosio testj EOS7tdB5cKCjhjZqyMNY9deCKD6CsHnxbdY9XE8k5vgAt3gLJwQWh
